document.write( '<script src=\'https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js\'></script>\n' );
document.write( '<style>\n' );
document.write( '/*  @import url(\'https://fonts.googleapis.com/css2?family=Arbutus&display=swap\');  */\n' );
document.write( '/* latin */\n' );
document.write( '@font-face {\n' );
document.write( '    	font-family: \'pageloader-js-font-family-sk\';\n' );
document.write( '    	font-style: normal;\n' );
document.write( '	   font-weight: 400;\n' );
document.write( '    	font-display: swap;\n' );
document.write( '	   src: url(https://fonts.gstatic.com/s/arbutus/v12/NaPYcZ7dG_5J3pooX9VnrgG_bMQ.woff2) format(\'woff2\');\n' );
document.write( '	unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;\n' );
document.write( '}\n' );
document.write( '.pageloader-js-power-by-sk {\n' );
document.write( '    	font-family: \'pageloader-js-font-family-sk\';\n' );
document.write( '     color: white;\n' );
document.write( '    	font-size: 14px;\n' );
document.write( '	    left: 50%;\n' );
document.write( '	    bottom: 1%;\n' );
document.write( '    	transform: translate(-50%, -50%);\n' );
document.write( '	    position: fixed;\n' );
document.write( '    	text-shadow: #808080 0 0 3px, #808080 0px 0 3px, #ffffff 0px 0 3px;\n' );
document.write( '}\n' );
document.write( '.pageloader-js-center-logo-image-sk {\n' );
document.write( '	    height: 200px;\n' );
document.write( '    	width: 200px;\n' );
document.write( '    	position: fixed;\n' );
document.write( '    	top: 45%;\n' );
document.write( '	    left: 50%;\n' );
document.write( '    	transform: translate(-50%, -50%);\n' );
document.write( '    	border-radius: 100px;\n' );
document.write( '	   -webkit-box-shadow: 0px 0px 8px 1px #f2f2f2;\n' );
document.write( '    	-moz-box-shadow: 0px 0px 8px 1px #f2f2f2;\n' );
document.write( '	    box-shadow: 0px 0px 8px 1px #f2f2f2;\n' );
document.write( '}\n' );
document.write( '#pageloader-js-bonfire-sk {\n' );
document.write( '     background-color: black;\n' );
document.write( '    	position: absolute;\n' );
document.write( '    	z-index: 99999999999999;\n' );
document.write( '    	width: 100%;\n' );
document.write( '	    height: 100%;\n' );
document.write( '	    left: 0;\n' );
document.write( '	    right: 0;\n' );
document.write( '    	top: 0;\n' );
document.write( '	    bottom: 0;\n' );
document.write( '}\n' );
document.write( '.pageloader-js-bonfire-fade-sk {\n' );
document.write( '	    opacity: 0 !important;\n' );
document.write( '	    -webkit-transition: all 1.5s ease;\n' );
document.write( '	    -moz-transition: all 1.5s ease;\n' );
document.write( '	    -o-transition: all 1.5s ease;\n' );
document.write( '	    -ms-transition: all 1.5s ease;\n' );
document.write( '	   transition: all 1.5s ease;\n' );
document.write( '}\n' );
document.write( '</style>\n' );
document.write( '<div id=\"pageloader-js-bonfire-sk\">\n' );
document.write( '     <img class=\"pageloader-js-center-logo-image-sk\" src=\"https://samsonkiran02.github.io/Link/Images/PNG/Samson-Kiran.png\" alt=\"Samson Kiran Logo\">\n' );
document.write( '     <p class=\"pageloader-js-power-by-sk\">Power By Samson Kiran</p>\n' );
document.write( '</div>\n' );
document.write( '<script>\n' );
document.write( '	jQuery(window).load(function () {\n' );
document.write( '	     setTimeout(function () {\n' );
document.write( '	          jQuery(\"#pageloader-js-bonfire-sk\").addClass(\'pageloader-js-bonfire-fade-sk\');\n' );
document.write( '	     }, 750);\n' );
document.write( '	     setTimeout(function () {\n' );
document.write( '	          jQuery(\"#pageloader-js-bonfire-sk\").addClass(\'pageloader-js-bonfire-hide-sk\');\n' );
document.write( '	     }, 1500);\n' );
document.write( '	});\n' );
document.write( '</script>' );
